# -*- coding: utf-8 -*-
"""Per-sekki content: seasonal tea flowers, chashaku names (銘),
bowl suggestions and caddy motifs — Japanese and English."""

# key, name, yomi, date, fire-class, fire-label, note, hana, mei, chawan, natsume
SEKKI_JA = [
("春 — SPRING", [
 ("risshun", "立春", "りっしゅん", "2月4日頃", "ro", "炉",
  "春の始まり。二月は大炉の季節。冬の名残と春の気配が同居する、一年でいちばん心の弾む頃。",
  "白玉椿・結び柳・水仙",
  "初音／東風(こち)／若緑／春の色",
  "筒茶碗から少し浅めへ。白釉や梅花皮(かいらぎ)の景色に春の光を。",
  "松竹梅・蕗の薹・青海波。まだ改まった意匠が似合う。"),
 ("usui", "雨水", "うすい", "2月19日頃", "ro", "炉",
  "雪が雨に変わる頃。雛の趣向がはじまり、貝合わせの香合が愛らしい季節。",
  "梅・猫柳・馬酔木(あせび)",
  "水温む／下萌(したもえ)／春霞／薄氷",
  "志野の白地に紅のにじみ。桃の絵付も雛の頃らしく。",
  "梅花・雪解・立雛。淡い蒔絵がよく映える。"),
 ("keichitsu", "啓蟄", "けいちつ", "3月6日頃", "ro", "炉",
  "虫が土から顔を出す頃。釣釜に替えて火を畳から離し、揺れる釜に春を感じる。",
  "土佐水木・雪柳・菜の花",
  "芽張柳(めはりやなぎ)／山笑う／日永／早蕨",
  "織部の緑釉。野の萌えを掌に。",
  "早蕨・若草・遠山。芽吹きの意匠を。"),
 ("shunbun", "春分", "しゅんぶん", "3月21日頃", "ro", "炉",
  "昼と夜が等しくなる彼岸の頃。月末の利休忌を控え、侘びた道具組が似合う。",
  "木蓮・彼岸桜・雪柳",
  "彼岸／花明かり／長閑(のどか)／初桜",
  "刷毛目や粉引の白に、ほのかな桜色を。",
  "桜・蝶・朧月。散り初めの花筏も。"),
 ("seimei", "清明", "せいめい", "4月5日頃", "ro", "炉",
  "すべてが清らかに明るくなる頃。透木釜(すきぎがま)で火を隠し、桜を存分に。",
  "山吹・木瓜(ぼけ)・都忘れ",
  "花衣／清明／春風／燕来(つばめきたる)",
  "唐津の斑(まだら)。花見の野点には替茶碗を数多く。",
  "花筏・燕・山吹。華やかな蒔絵の見せどころ。"),
 ("kokuu", "穀雨", "こくう", "4月20日頃", "nagori", "炉の名残",
  "春の雨が田畑を潤す頃。炉の季節の終わり、八十八夜の新茶に思いを寄せて。",
  "牡丹・藤・著莪(しゃが)",
  "春雨／緑雨／惜春／藤浪",
  "井戸の枇杷色。名残の炉に温かみを。",
  "藤・菜種・雨龍。しっとりした意匠を。"),
]),
("夏 — SUMMER", [
 ("rikka", "立夏", "りっか", "5月6日頃", "fu", "風炉",
  "初風炉。しつらえを一新し、火を客から遠ざける。一年の折り返し。",
  "都忘れ・鉄線(クレマチス)・白山吹",
  "薫風／初風炉／若楓／青葉",
  "平茶碗へ。青磁や染付の涼しさが立つ。",
  "若葉・流水・菖蒲。爽やかな意匠に替える。"),
 ("shoman", "小満", "しょうまん", "5月21日頃", "fu", "風炉",
  "万物が満ち満ちる頃。新茶の季節、青竹の蓋置が瑞々しい。",
  "卯の花・額紫陽花・蛍袋",
  "卯の花／青嵐／走り梅雨／新茶",
  "刷毛目の白。若葉の色を茶で映す。",
  "卯の花・青楓・早苗。白と緑の取り合わせ。"),
 ("boshu", "芒種", "ぼうしゅ", "6月6日頃", "fu", "風炉",
  "稲を植える頃、梅雨の入り。雨音を楽しむ道具組を。",
  "半夏生・蛍袋・擬宝珠(ぎぼうし)",
  "早苗／蛍／水無月／雨蛙",
  "絵唐津の平茶碗。雨のにじみのような釉を。",
  "蛍・早苗・水紋。夜の趣向にも。"),
 ("geshi", "夏至", "げし", "6月21日頃", "fu", "風炉",
  "一年で最も昼が長い日。目にも涼しい取り合わせを。",
  "紫陽花・半夏生・桔梗の走り",
  "短夜(みじかよ)／青田／清流／滴",
  "平茶碗、義山(ぎやまん=硝子)も。見込みの広さで涼を。",
  "紫陽花・蛇の目傘・観世水。"),
 ("shosho_s", "小暑", "しょうしょ", "7月7日頃", "fu", "風炉",
  "七夕。梶の葉の趣向、葉蓋の点前で涼一味。朝茶事の季節が始まる。",
  "木槿(むくげ)・桔梗・姫百合",
  "天の川／笹の葉／涼風／星合",
  "朝顔形の平茶碗。朝茶には白い器を。",
  "七夕・笹・星。短冊の意匠も涼しい。"),
 ("taisho", "大暑", "たいしょ", "7月23日頃", "fu", "風炉",
  "暑さの極み。名水点(めいすいだて)や洗い茶巾で、水そのものを馳走に。",
  "蓮・木槿・糸芒",
  "滝／清涼／蝉時雨／井筒",
  "硝子茶碗。洗い茶巾の点前で水音を聞かせる。",
  "流水・蓮・瀧。銀の蒔絵が涼やか。"),
]),
("秋 — AUTUMN", [
 ("risshu", "立秋", "りっしゅう", "8月8日頃", "fu", "風炉",
  "暦の上の秋。残暑の中に秋草をひとつ忍ばせるのが心憎い。",
  "桔梗・女郎花(おみなえし)・芙蓉",
  "初秋／残暑／秋の声／新涼",
  "まだ平茶碗。土の色に秋の気配を。",
  "秋草・萩・露芝。ひと足早く秋を。"),
 ("shosho_a", "処暑", "しょしょ", "8月23日頃", "fu", "風炉",
  "暑さがおさまる頃。虫の音が主役になる。",
  "萩・芒・水引",
  "露涼し／初萩／盆の月／虫の音",
  "萩焼の枇杷色。使うほどに育つ器を。",
  "萩・芒・武蔵野。金銀の蒔絵で野を描く。"),
 ("hakuro", "白露", "はくろ", "9月8日頃", "fu", "風炉",
  "露が白く光る頃。月の意匠が主役に。",
  "芒・桔梗・藤袴",
  "白露／初雁／月白／露の宿",
  "深めに戻る。粉引や刷毛目の土味を。",
  "露芝・月・雁。銀月の蒔絵をひとつ。"),
 ("shubun", "秋分", "しゅうぶん", "9月23日頃", "fu", "風炉(中置)",
  "名月の頃。風炉を畳の中央に寄せる「中置」で、火を少し客に近づける。",
  "秋海棠・竜胆(りんどう)・水引",
  "月影／豊の秋／彼岸／千草",
  "唐津・粉引。月を映すような静かな見込みを。",
  "月兎・薄・秋の七草。"),
 ("kanro", "寒露", "かんろ", "10月8日頃", "fu", "風炉(中置)",
  "露が冷たくなる頃。実りと紅葉の意匠へ。",
  "秋明菊・杜鵑草(ほととぎす)・野菊",
  "名残／うそ寒／木の実／照葉",
  "雨漏(あまもり)茶碗や割高台。侘びた景色を愛でる。",
  "木の実・菊・破れ袋。侘びた意匠が似合う。"),
 ("soko", "霜降", "そうこう", "10月23日頃", "nagori", "名残",
  "風炉の名残。中板・小板に破れ風炉、一年で最も渋い茶を楽しむ。",
  "照葉・野菊・藤袴",
  "名残の月／初霜／山粧う／木枯",
  "継いだ茶碗も景色として。侘びの極み。",
  "落葉・蔦・霜。使い込んだ塗りがふさわしい。"),
]),
("冬 — WINTER", [
 ("ritto", "立冬", "りっとう", "11月7日頃", "ro", "炉",
  "炉開き・口切の茶事。茶人の正月。新しい茶壺を開け、善哉で祝う。",
  "侘助椿・照葉・山茶花",
  "口切／亥の子／開炉／初炉",
  "筒茶碗へ。楽茶碗の温もりが恋しくなる。",
  "松・常盤・宝尽くし。改まった意匠で。"),
 ("shosetsu", "小雪", "しょうせつ", "11月22日頃", "ro", "炉",
  "初時雨の頃。照葉と初雪が同じ景色に並ぶ。",
  "山茶花・柊・南天",
  "初雪／冬紅葉／埋み火／時雨",
  "織部の沓(くつ)茶碗。歪みの景色が映える。",
  "雪輪・南天・松葉。白と朱の対比を。"),
 ("taisetsu", "大雪", "たいせつ", "12月7日頃", "ro", "炉",
  "本格的な冬。日が短く、夜咄(よばなし)の茶事へ。短檠の灯りで囲む一服。",
  "蝋梅・水仙・寒椿",
  "埋火／雪明かり／閑(しずか)／夜咄",
  "筒茶碗。湯が冷めにくい深い器を。",
  "雪持笹・千鳥・寒牡丹。灯に映える溜塗を。"),
 ("toji", "冬至", "とうじ", "12月22日頃", "ro", "炉",
  "一陽来復。柚子の香合で無病息災を願い、太陽の還りを祝う。",
  "寒菊・南天・柚子",
  "一陽来復／柚子／長夜／福寿",
  "黒楽の温み。掌がいちばんありがたい季節。",
  "一陽来復・日の出・南天。祝いの意匠を。"),
 ("shokan", "小寒", "しょうかん", "1月6日頃", "ro", "炉",
  "寒の入り、初釜の季節。結び柳に嶋台茶碗、晴れやかな正月のしつらえ。",
  "結び柳・白玉椿・福寿草",
  "松の内／初春／寿／蓬莱",
  "嶋台茶碗(金銀の重ね)。赤楽で祝いの色を。",
  "松竹梅・宝尽くし・干支。一年で最も華やかに。"),
 ("daikan", "大寒", "だいかん", "1月20日頃", "ro", "炉",
  "寒さの極み。筒茶碗に絞り茶巾の点前で、湯気ごと温かさを差し出す。",
  "侘助・蝋梅・猫柳",
  "寒紅梅／冬木立／待春／氷解",
  "筒茶碗に絞り茶巾。手のひらの温度で客をもてなす。",
  "雪輪・寒梅・松。静かな意匠で春を待つ。"),
]),
]

# key, kanji, romaji-gloss, date, fire-class, fire-label, note, flowers, names, bowl, caddy
SEKKI_EN = [
("SPRING", [
 ("risshun", "立春", "RISSHUN — spring begins", "c. Feb 4", "ro", "RO",
  "Spring on the calendar. February brings the great hearth; winter's last breath and the first hint of spring share one room.",
  "White camellia, looped willow, narcissus",
  "Hatsune (first birdsong) / Kochi (east wind) / Wakamidori (young green)",
  "Still deep, but easing open. White glaze or crawled kairagi glaze catches the new light.",
  "Pine-bamboo-plum, butterbur bud, seigaiha waves — formal motifs still suit."),
 ("usui", "雨水", "USUI — snow turns to rain", "c. Feb 19", "ro", "RO",
  "Snow softens into rain. The Dolls' Festival arrives, and shell-pair incense boxes charm the room.",
  "Plum, pussy willow, andromeda (asebi)",
  "Mizu nurumu (water warms) / Shitamoe (shoots below) / Harugasumi (spring haze)",
  "Shino's white ground with a blush of red; peach painting suits the Dolls' season.",
  "Plum blossom, thawing snow, standing dolls — pale maki-e shines here."),
 ("keichitsu", "啓蟄", "KEICHITSU — insects wake", "c. Mar 6", "ro", "RO",
  "Creatures stir from the earth. The hanging kettle lifts the fire off the mat and sways with the season.",
  "Corylopsis, spiraea, rape blossom",
  "Meharu-yanagi (budding willow) / Yama warau (the hills smile) / Sawarabi (young bracken)",
  "Oribe's green glaze — the meadow's first flush, held in the hand.",
  "Bracken fronds, young grass, distant hills — the motifs of budding."),
 ("shunbun", "春分", "SHUNBUN — spring equinox", "c. Mar 21", "ro", "RO",
  "Day and night in balance. With Rikyū's memorial at month's end, a quiet, wabi arrangement suits.",
  "Magnolia, equinox cherry, spiraea",
  "Higan (the equinox week) / Hana-akari (blossom glow) / Nodoka (serene)",
  "Brushed-slip or kohiki white, warmed by the faintest cherry tint.",
  "Cherry, butterfly, hazy moon — and rafts of fallen petals."),
 ("seimei", "清明", "SEIMEI — clear and bright", "c. Apr 5", "ro", "RO",
  "All things turn clear and bright. The sukigi kettle hides the fire so the cherry blossom can hold the room.",
  "Kerria, flowering quince, gentian-aster",
  "Hanagoromo (blossom robe) / Seimei / Harukaze (spring wind)",
  "Karatsu's mottled madara. For outdoor tea, keep many spare bowls at hand.",
  "Petal rafts, swallows, kerria — the showpiece season for gold maki-e."),
 ("kokuu", "穀雨", "KOKUU — grain rains", "c. Apr 20", "nagori", "LAST RO",
  "Spring rain feeds the fields. The hearth season closes; thoughts turn to the 88th-night new tea.",
  "Peony, wisteria, fringed iris (shaga)",
  "Harusame (spring rain) / Ryokuu (green rain) / Sekishun (spring regretted)",
  "Ido's loquat-gold. Warmth for the hearth's final weeks.",
  "Wisteria, rape seed, rain dragon — softer, damper motifs."),
]),
("SUMMER", [
 ("rikka", "立夏", "RIKKA — summer begins", "c. May 6", "fu", "FURO",
  "The first brazier. The whole room is refitted and the fire moves away from the guests — the year's halfway turn.",
  "Gentian-aster, clematis, white kerria",
  "Kunpū (fragrant breeze) / Hatsu-buro (first brazier) / Wakakaede (young maple)",
  "Now the shallow bowl. Celadon and blue-and-white read as cool.",
  "Young leaves, flowing water, iris — the motifs are refreshed entirely."),
 ("shoman", "小満", "SHŌMAN — all things fill", "c. May 21", "fu", "FURO",
  "Everything comes to fullness. New-tea season, and a green bamboo lid rest looks freshly cut.",
  "Deutzia, lacecap hydrangea, campanula",
  "Unohana (deutzia) / Seiran (green squall) / Shincha (new tea)",
  "Brushed white slip — the colour of young leaves answered in the tea.",
  "Deutzia, green maple, rice seedlings — white against green."),
 ("boshu", "芒種", "BŌSHU — grain in ear", "c. Jun 6", "fu", "FURO",
  "Rice is planted and the rains arrive. Choose utensils that enjoy the sound of water.",
  "Hangeshō, campanula, hosta",
  "Sanae (rice seedlings) / Hotaru (firefly) / Minazuki",
  "Painted Karatsu, shallow — a glaze that bleeds like rain on paper.",
  "Fireflies, seedlings, ripples — good for an evening gathering too."),
 ("geshi", "夏至", "GESHI — summer solstice", "c. Jun 21", "fu", "FURO",
  "The longest day. Everything is chosen to look cool.",
  "Hydrangea, hangeshō, the first bellflowers",
  "Mijikayo (short night) / Aota (green paddy) / Seiryū (clear stream)",
  "A shallow bowl, or glass. Coolness comes from the width of the well.",
  "Hydrangea, janome umbrella, kanze water-swirls."),
 ("shosho_s", "小暑", "SHŌSHO — lesser heat", "c. Jul 7", "fu", "FURO",
  "Tanabata. The leaf-lid procedure brings a breath of cool, and dawn tea gatherings begin.",
  "Rose of Sharon, bellflower, star lily",
  "Amanogawa (Milky Way) / Sasa no ha (bamboo leaf) / Ryōfū (cool wind)",
  "A morning-glory-shaped shallow bowl; white ware for dawn tea.",
  "Tanabata, bamboo grass, stars — even the paper-strip motif reads cool."),
 ("taisho", "大暑", "TAISHO — greater heat", "c. Jul 23", "fu", "FURO",
  "Peak heat. The famous-water and rinsed-cloth procedures make water itself the treat.",
  "Lotus, rose of Sharon, thread grass",
  "Taki (waterfall) / Seiryō (pure cool) / Semi-shigure (cicada rain)",
  "A glass bowl. The rinsed-cloth procedure lets the guests hear the water.",
  "Flowing water, lotus, waterfall — silver maki-e feels coolest."),
]),
("AUTUMN", [
 ("risshu", "立秋", "RISSHŪ — autumn begins", "c. Aug 8", "fu", "FURO",
  "Autumn on the calendar. Slipping one autumn grass in among the lingering heat is the elegant move.",
  "Bellflower, golden lace (ominaeshi), hibiscus",
  "Shoshū (early autumn) / Zansho (lingering heat) / Aki no koe (autumn's voice)",
  "Still a shallow bowl, but earth-toned — autumn arrives in the clay.",
  "Autumn grasses, bush clover, dewy grass — a half-step ahead of the season."),
 ("shosho_a", "処暑", "SHOSHO — heat retreats", "c. Aug 23", "fu", "FURO",
  "The heat withdraws and insect voices take the lead.",
  "Bush clover, pampas grass, mizuhiki",
  "Tsuyu suzushi (cool dew) / Hatsu-hagi (first clover) / Mushi no ne (insect song)",
  "Hagi ware's loquat tone — a bowl that ripens with use.",
  "Clover, pampas, the Musashino plain drawn in gold and silver."),
 ("hakuro", "白露", "HAKURO — white dew", "c. Sep 8", "fu", "FURO",
  "Dew glints white on the grass. Moon motifs take the lead.",
  "Pampas grass, bellflower, boneset (fujibakama)",
  "Hakuro (white dew) / Hatsukari (first geese) / Geppaku (moon-white)",
  "Deepening again. Kohiki and brushed slip bring back the taste of earth.",
  "Dewy grass, moon, wild geese — one silver moon is enough."),
 ("shubun", "秋分", "SHŪBUN — autumn equinox", "c. Sep 23", "fu", "NAKAOKI",
  "Harvest-moon weeks. The brazier moves to the mat's centre (nakaoki), edging the fire toward the guests.",
  "Hardy begonia, gentian, mizuhiki",
  "Tsukikage (moonlight) / Toyo no aki (abundant autumn) / Chigusa (thousand grasses)",
  "Karatsu or kohiki — a still, quiet well that could hold the moon.",
  "Moon-rabbit, pampas, the seven autumn grasses."),
 ("kanro", "寒露", "KANRO — cold dew", "c. Oct 8", "fu", "NAKAOKI",
  "The dew turns cold. Motifs move to fruit and turning leaves.",
  "Japanese anemone, toad lily, wild chrysanthemum",
  "Nagori (what remains) / Usosamu (a touch cold) / Ki no mi (nuts and berries)",
  "A rain-stained amamori bowl or split foot — wabi landscapes to savour.",
  "Nuts, chrysanthemum, the torn bag — worn motifs suit this month."),
 ("soko", "霜降", "SŌKŌ — frost falls", "c. Oct 23", "nagori", "NAGORI",
  "The brazier's farewell. A broken brazier on a small board: the year's most austere tea.",
  "Turning leaves, wild chrysanthemum, boneset",
  "Nagori no tsuki (parting moon) / Hatsushimo (first frost) / Yama yosou (hills adorned)",
  "Even a mended bowl counts as landscape now — wabi at its deepest.",
  "Fallen leaves, ivy, frost — well-worn lacquer is exactly right."),
]),
("WINTER", [
 ("ritto", "立冬", "RITTŌ — winter begins", "c. Nov 7", "ro", "RO",
  "Hearth-opening and the jar-cutting gathering: the tea person's New Year. A new tea jar is broached and sweet zenzai served.",
  "Wabisuke camellia, turning leaves, sasanqua",
  "Kuchikiri (jar cutting) / I-no-ko (boar day) / Kairo (hearth opened)",
  "To the deep cylinder bowl. Raku's warmth becomes something you long for.",
  "Pine, evergreen, the treasure motifs — formal designs for a formal day."),
 ("shosetsu", "小雪", "SHŌSETSU — light snow", "c. Nov 22", "ro", "RO",
  "First cold showers. Turning leaves and first snow share the same view.",
  "Sasanqua, holly, nandina",
  "Hatsuyuki (first snow) / Fuyu-momiji (winter maple) / Uzumibi (banked embers)",
  "Oribe's shoe-shaped bowl — its deliberate distortion comes alive.",
  "Snow-ring, nandina, pine needle — white played against vermilion."),
 ("taisetsu", "大雪", "TAISETSU — heavy snow", "c. Dec 7", "ro", "RO",
  "Deep winter. Days shorten toward the night gathering (yobanashi), a bowl shared by lamplight.",
  "Wintersweet, narcissus, winter camellia",
  "Uzumibi (banked fire) / Yuki-akari (snow light) / Yobanashi (night talk)",
  "The cylinder bowl — deep enough to keep the tea hot.",
  "Snow-laden bamboo, plover, winter peony — tame-nuri glows under lamps."),
 ("toji", "冬至", "TŌJI — winter solstice", "c. Dec 22", "ro", "RO",
  "The light returns (ichiyō raifuku). A yuzu incense box wishes health, and the sun's turn is celebrated.",
  "Winter chrysanthemum, nandina, yuzu",
  "Ichiyō raifuku (light returns) / Yuzu / Nagayo (long night)",
  "Black Raku's warmth — the season the palms are most grateful.",
  "The returning light, sunrise, nandina — motifs of celebration."),
 ("shokan", "小寒", "SHŌKAN — lesser cold", "c. Jan 6", "ro", "RO",
  "The cold sets in and the year's first kettle is hung. Looped willow and stacked shimadai bowls: New Year at its brightest.",
  "Looped willow, white camellia, pheasant's eye (fukujusō)",
  "Matsu-no-uchi (the pine days) / Hatsuharu (new spring) / Kotobuki (felicity)",
  "The gold-and-silver shimadai pair; red Raku for a festive colour.",
  "Pine-bamboo-plum, treasure motifs, the zodiac — the year's most lavish."),
 ("daikan", "大寒", "DAIKAN — greatest cold", "c. Jan 20", "ro", "RO",
  "The deepest cold. The cylinder bowl and wrung-cloth procedure hand the guest warmth along with the steam.",
  "Wabisuke camellia, wintersweet, pussy willow",
  "Kan-kōbai (winter red plum) / Fuyu-kodachi (bare grove) / Machiharu (awaiting spring)",
  "Cylinder bowl with the wrung cloth — the host's own warmth is the welcome.",
  "Snow-ring, winter plum, pine — quiet motifs while spring is awaited."),
]),
]
